spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
              - profile_image
            client-name: Kakao
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  secret: ${JWT_SECRET:c2VjdXJpdHkta2V5LWZvci1sb3R0by1hcHBsaWNhdGlvbi13aXRoLWp3dC10b2tlbi1tYW5hZ2VtZW50}
  token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 2592000  # 30일
  
app:
  auth:
    token-secret: ${TOKEN_SECRET:auth-token-secret-key-for-lottomate-application}
    token-expiration-msec: 864000000  # 10일
    refresh-token-expiration-msec: 2592000000  # 30일
  oauth2:
    authorized-redirect-uris:
      - https://lottomate.eeerrorcode.com/oauth2/redirect
      - http://localhost:3000/oauth2/redirect