spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} 
    include:
    - database
    - iamport
  application:
    name: lottomate
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:mariadb://${RDS_ENDPOINT}:3306/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      - templates
    livereload:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    root: 
      info
    jdbc.audit: WARN
    jdbc.connection: WARN
    jdbc.resultset: WARN
    jdbc.sqltiming: WARN
    com.zaxxer.hikari: WARN
    jdbc.sqlonly: WARN
    org.hibernate: WARN
app:
  domain: https://lottomate.eeerrorcode.com

# JWT와 OAuth2 기본 설정 - 배포 환경에서 환경 변수로 덮어씀
jwt:
  secret: ${JWT_SECRET:default-insecure-key}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_SECONDS:86400}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_SECONDS:2592000}

oauth2:
  client:
    registration:
      google:
        client-id: ${GOOGLE_CLIENT_ID:default-google-id}
        client-secret: ${GOOGLE_CLIENT_SECRET:default-google-secret}
        redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/oauth2/callback/google}
        scope:
          - email
          - profile
      kakao:
        client-id: ${KAKAO_CLIENT_ID:default-kakao-id}
        client-secret: ${KAKAO_CLIENT_SECRET:default-kakao-secret}
        redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/oauth2/callback/kakao}
        scope:
          - account_email
          - profile_nickname
          - profile_image
    provider:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-name-attribute: id