# docker.yml

name: Deploy Spring Boot to Docker Hub

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_NAME: junyoonn/lottomate
  DOCKER_TAG: latest
  CONTAINER_NAME: lottomate-backend-container

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.13

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }} \
          --build-arg RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
          --build-arg RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
          --build-arg RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
          -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }} .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}

  deploy-to-ec2:
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          CONTAINER_NAME="${{ env.CONTAINER_NAME }}"
          IMAGE_NAME="${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}"

          # 기존 컨테이너 중지 및 삭제
          if sudo docker ps -a --format "{{.Names}}" | grep -w "$CONTAINER_NAME"; then
            echo "Stopping and removing existing container: $CONTAINER_NAME"
            sudo docker stop $CONTAINER_NAME
            sudo docker rm $CONTAINER_NAME
          fi
          
          # 최신 이미지 Pull
          echo "Pulling the latest Docker image: $IMAGE_NAME"
          sudo docker pull $IMAGE_NAME
          
          # 새 컨테이너 실행 
          echo "Starting a new container: $CONTAINER_NAME"
          sudo docker run -d \
            --name $CONTAINER_NAME \
            -p 8082:8080 \
            -e RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
            -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            $IMAGE_NAME